# Generated by Django 5.2.8 on 2025-11-19 07:03

import VenuesApp.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Le nom du décor est obligatoire.'}, max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÖØ-öø-ÿ\\s\\-]+$', 'Le nom doit contenir uniquement des lettres, espaces ou tirets.')])),
                ('category', models.CharField(choices=[('floral', 'Décor Floral'), ('table', 'Décor de Table'), ('lighting', 'Éclairage'), ('stage', 'Scène / Podium'), ('entrance', 'Entrée / Accueil'), ('traditional', 'Traditionnel'), ('modern', 'Moderne')], error_messages={'blank': 'La catégorie est obligatoire.'}, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, error_messages={'blank': 'Le prix est obligatoire.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(error_messages={'blank': "L'image du décor est obligatoire."}, null=True, upload_to='decors/', validators=[VenuesApp.models.validate_image_format])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_v', models.CharField(error_messages={'blank': 'Le nom du venue est obligatoire.'}, max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÖØ-öø-ÿ\\s\\-]+$', 'Le nom doit contenir uniquement des lettres, espaces ou tirets.')])),
                ('adresse_v', models.CharField(error_messages={'blank': "L'adresse du venue est obligatoire."}, max_length=300)),
                ('nb_place', models.PositiveIntegerField(error_messages={'blank': 'Le nombre de places est obligatoire.'}, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(error_messages={'blank': "L'image du venue est obligatoire."}, null=True, upload_to='venues/', validators=[VenuesApp.models.validate_image_format])),
                ('prix', models.DecimalField(decimal_places=2, error_messages={'blank': 'Le prix du venue est obligatoire.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(50)])),
                ('email', models.EmailField(error_messages={'blank': "L'email du venue est obligatoire."}, max_length=254)),
                ('type', models.CharField(choices=[('wedding_hall', 'Salle de mariage'), ('luxury_hotel', 'Hôtel de luxe'), ('outdoor', 'Espace extérieur'), ('garden', 'Jardin'), ('castle', 'Château'), ('ballroom', 'Salle de réception'), ('restaurant', 'Restaurant')], error_messages={'blank': 'Le type de venue est obligatoire.'}, max_length=120)),
                ('description', models.TextField(error_messages={'blank': 'La description du venue est obligatoire.'}, validators=[django.core.validators.MinLengthValidator(31)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decor', models.ForeignKey(error_messages={'blank': 'Le décor est obligatoire.'}, on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='VenuesApp.decor')),
            ],
        ),
        migrations.CreateModel(
            name='VenueReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('start_time', models.TimeField(blank=True, default=datetime.time(12, 0), null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('nom_reservation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='EventApp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_reservations', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='VenuesApp.venue')),
            ],
        ),
    ]
