# Generated by Django 5.2.8 on 2025-11-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
        ('VenuesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuereservation',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='EventApp.event'),
        ),
    ]
