# Generated by Django 5.2.9 on 2025-12-05 02:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('type_animation', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True)),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacite_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('interieur_exterieur', models.CharField(choices=[('interieur', 'Intérieur'), ('exterieur', 'Extérieur'), ('mixte', 'Mixte')], default='mixte', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animateurs/')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('tags_auto', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationAnim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=140, validators=[django.core.validators.MinLengthValidator(2)])),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='brouillon', max_length=12)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='AnimationApp.animateur')),
                ('id_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_animation', to='EventApp.event')),
            ],
        ),
    ]
