# Generated by Django 5.2.8 on 2025-11-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimationApp', '0001_initial'),
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationanim',
            name='id_evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_animation', to='EventApp.event'),
        ),
    ]
