# Generated by Django 5.2.8 on 2025-11-07 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÖØ-öø-ÿ\\s\\-]+$', 'Name must contain only letters, spaces or hyphens.')])),
                ('category', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='decors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_v', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÖØ-öø-ÿ\\s\\-]+$', 'Name must contain only letters, spaces or hyphens.')])),
                ('adresse_v', models.CharField(max_length=300)),
                ('nb_place', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=120)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(31)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='VenuesApp.decor')),
            ],
        ),
    ]
