# Generated by Django 5.2.8 on 2025-11-12 18:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
        ('UserApp', '0002_rename_appuser_user_alter_user_options'),
        ('VenuesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('start_time', models.TimeField(blank=True, default=datetime.time(12, 0), null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('nom_reservation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='EventApp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_reservations', to='UserApp.user')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='VenuesApp.venue')),
            ],
        ),
    ]
