# Generated by Django 5.2.8 on 2025-11-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CateringAPP', '0002_cateringreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringreservation',
            name='menu_item',
        ),
    ]
