# Generated by Django 5.2.8 on 2025-11-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'M.'), ('mrs', 'Mme'), ('ms', 'Mlle'), ('dr', 'Dr'), ('prof', 'Prof')], default='mr', max_length=10, verbose_name='Titre')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entreprise')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poste')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('declined', 'Décliné'), ('attended', 'Présent'), ('absent', 'Absent')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('plus_one', models.BooleanField(default=False, verbose_name='Accompagnateur')),
                ('dietary_restrictions', models.TextField(blank=True, null=True, verbose_name='Restrictions alimentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='InvitationAPP.invitation', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Invité',
                'verbose_name_plural': 'Invités',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('invitation', 'email')},
            },
        ),
    ]
