# Generated by Django 5.2.8 on 2025-11-20 20:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
        ('InvitationAPP', '0002_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('start_time', models.TimeField(blank=True, default=datetime.time(12, 0), null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('nom_reservation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_invitation', to='EventApp.event')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='InvitationAPP.invitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
