# Generated by Django 5.2.8 on 2025-11-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
        ('InvitationAPP', '0003_invitationreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='EventApp.event'),
        ),
        migrations.DeleteModel(
            name='InvitationReservation',
        ),
    ]
