# Generated by Django 5.2.8 on 2025-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationAPP', '0004_invitation_event_delete_invitationreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
