# Generated by Django 5.2.8 on 2025-11-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationAPP', '0005_invitation_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='dress_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
