# Generated by Django 5.2.8 on 2025-11-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationAPP', '0006_invitation_dress_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='location',
        ),
    ]
