# Generated by Django 5.2.6 on 2025-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
