# Generated by Django 5.2.8 on 2025-11-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nom'], 'verbose_name': 'User (app)', 'verbose_name_plural': 'Users (app)'},
        ),
    ]
