# Generated by Django 5.2.8 on 2025-11-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('type_animation', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacite_max', models.PositiveIntegerField()),
                ('interieur_exterieur', models.CharField(choices=[('interieur', 'Intérieur'), ('exterieur', 'Extérieur'), ('mixte', 'Mixte')], default='mixte', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('tags_auto', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationAnim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evenement', models.CharField(blank=True, max_length=64)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=140)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='brouillon', max_length=12)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='AnimationApp.animateur')),
            ],
        ),
    ]
