# Generated by Django 5.2.8 on 2025-11-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animateurs/'),
        ),
    ]
